# -*- coding: utf-8 -*-
{
    'name': "Gigi's Corner – Portal Web",
    'summary': "Sitio web completo. 100% Odoo 17 Community.",
    'author': "Gigi's Corner",
    'website': "https://gigiscorner.com.mx",
    'category': 'Website',
    'version': '17.0.1.0.0',
    'depends': ['website', 'mail', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'data/gigis_data.xml',
        'views/gigis_assets.xml',
        'views/gigis_templates.xml',
        'views/gigis_home.xml',
        'views/gigis_historias.xml',
        'views/gigis_nosotros.xml',
        'views/gigis_personalizado.xml',
        'views/gigis_menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
